### PR TITLE
[WIP] Fix build on Q and R

### PR DESCRIPTION
**Pull request by ix5**
Because a certain Italian decided to take their 5kg projector over of a proper device, like, say, a beautiful **TONE** phone into exile, here's something that should make him happy ;)

### CODE REVIEW

**Comment by kholk** [comment]
I'm happy :p

.... But I can't test it now :/

**Comment by MarijnS95** [comment]
@kholk I know you're short on time... But now is the right time to test this :)

**Comment by ix5** [comment]
We might as well drop projection from `local_manifests` and ucommsvr from packages since blanc won't be getting R.

**Comment by MarijnS95** [comment]
@ix5 That might be a way to pressure reviewers...

In all seriousness it'd be nice to push this cleanup through anyway; you spent good time on it as well.

**Comment by Haxk20** [comment]
@ix5 Does this sound good ?
[Remove projection from local_manifests](https://github.com/sonyxperiadev/local_manifests/pull/108)

**Comment by ix5** [comment]
@kholk in case you still want this please test, you might be the only person on this planet with a blanc

**Comment by ix5** [comment]
`:sad-trumpet:`

**Pull request closed without merging**
